/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Error response model for API errors.
 */
export interface ErrorResponse {

  /**
   * Additional error details
   */
  details?: ({
[key: string]: any;
} | null);

  /**
   * Error type or category
   */
  error: string;

  /**
   * Detailed error message
   */
  message: string;
}
