/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Supported timeframes for simulation.
 */
export enum Timeframe {
  $1M = '1m',
  $5M = '5m',
  $15M = '15m',
  $30M = '30m',
  $1H = '1h',
  $2H = '2h',
  $4H = '4h',
  $1D = '1d'
}
